domain/src/main/java/life/qbic/usermanagement/policies/PasswordEncryptionPolicy.java
domain/src/test/groovy/life/qbic/usermanagement/policies/PasswordEncryptionPolicySpec.groovy

Change encryption method from PBKDF2 to PBE because of reported security vulnerability issues (see https://github.com/qbicsoftware/data-manager-app/security/code-scanning/1)
I also increased the iterations as well

Change encryption method

---

domain/src/main/java/life/qbic/events/DomainEvent.java
domain/src/main/java/life/qbic/usermanagement/registration/UserRegistered.java

Adds domain event interface and an example implementation

Add domain event

---

domain/src/main/java/life/qbic/apps/datamanager/services/UserRegistrationService.java
domain/src/main/java/life/qbic/domain/user/User.java
domain/src/main/java/life/qbic/domain/user/UserDomainService.java
domain/src/main/java/life/qbic/domain/user/UserId.java
domain/src/main/java/life/qbic/domain/user/jpa/EmailConverter.java
domain/src/main/java/life/qbic/domain/user/jpa/FullNameConverter.java
domain/src/main/java/life/qbic/domain/usermanagement/registration/Registration.java
domain/src/main/java/life/qbic/domain/usermanagement/repository/UserDataStorage.java
domain/src/main/java/life/qbic/domain/usermanagement/repository/UserRepository.java
domain/src/test/groovy/life/qbic/domain/user/UserSpec.groovy
domain/src/test/groovy/life/qbic/domain/usermanagement/registration/RegistrationSpec.groovy
domain/src/test/groovy/life/qbic/domain/usermanagement/repository/UserRepositorySpec.groovy
webapp/src/main/java/life/qbic/usermanagement/persistence/QbicUserRepo.java
webapp/src/main/java/life/qbic/usermanagement/persistence/UserJpaRepository.java

To make user object a conceptual whole value object, the String user id is converted to a DDD object UserId, using the domain language.

Introduce UserId concept

---

core/src/main/java/life/qbic/identityaccess/domain/user/PasswordReset.java
core/src/main/java/life/qbic/identityaccess/domain/user/User.java
core/src/test/groovy/life/qbic/domain/user/UserSpec.groovy
webapp/src/main/test/life/qbic/events/DomainEventSerializerSpec.groovy
webapp/src/main/test/life/qbic/events/EventStoreSpec.groovy

This PR adds only the domain model for the user's password request.

Add domain model that includes the password reset

---

core/src/main/java/life/qbic/identityaccess/application/user/PasswordResetInput.java
core/src/main/java/life/qbic/identityaccess/application/user/PasswordResetRequest.java
core/src/main/java/life/qbic/identityaccess/application/user/UserRegistrationService.java

Since user do provide an email address and not their id, the use case
needs to be adjusted.

Correct the use case input parameter

---

webapp/src/main/resources/logback-spring.xml

Via the env var `$DM_LOG_PATH`

Enable configuration for logging

---

projectmanagement/src/main/java/life/qbic/projectmanagement/application/ProjectCreationService.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/CreateProjectHandler.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/CreateProjectLayout.java

Implement length check in UI

---

vaadinfrontend/src/main/java/life/qbic/datamanager/ClientDetailsProvideImpl.java
vaadinfrontend/src/main/java/life/qbic/datamanager/ClientDetailsProvider.java
vaadinfrontend/src/main/java/life/qbic/datamanager/ClientDetailsProviderImpl.java
vaadinfrontend/src/main/java/life/qbic/datamanager/MyVaadinSessionInitListener.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/overview/ProjectOverviewLayout.java

This PR tries to query the client details for displaying the date in the zone of the client. It falls back to UTC

Format modification time according to user timezone

---

subscription-provider/src/main/java/life/qbic/logging/subscription/provider/mail/property/MailPropertyLoader.java
subscription-provider/src/main/java/life/qbic/logging/subscription/provider/mail/property/PropertyFileParser.java

Fixes the app not being able to read from the mail.properties file when
compiled and package to a running jar file.

Load mail.properties from resources

---

projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/ProjectCode.java
projectmanagement/src/test/java/life/qbic/projectmanagement/domain/project/ProjectCodeSpec.groovy

Provides a new domain value object ProjectCode, that enables
to create random codes, exclude blacklisted expressions and can
parse valid codes from String representations.

Introduce ProjectCode class

---

projectmanagement/src/main/java/life/qbic/projectmanagement/application/ProjectInformationService.java
projectmanagement/src/main/java/life/qbic/projectmanagement/application/ProjectLinkingService.java
projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/Project.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/ContactElement.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/PersonElement.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/view/components/ProjectDetailsComponent.java

Introduce PersonElement, which renders the person and email contact nicely. 
Furthermore, since the combobox ItemLabel can only be a string and no styling is possible a component switch is introduced to show the selected project manager.

Improved project manager selection in project view

---

vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/ProjectInformationDialog.java

Set experimental design to empty after selecting an offer without ED during project creation

---

vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/ProjectInformationDialog.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/overview/components/ProjectOverviewComponent.java

Change project creation dialogue to have a min-width of 2/3 of the screen size 

---

vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/ProjectInformationDialog.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/overview/components/ProjectOverviewComponent.java

Resets the project creation dialogue if the project was created successfully 👍

Reset ProjectDialogue after successful project Creation

---

vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/ProjectNavigationBarComponent.java

remove padding of sub-layouts, add convenience method to style them

reduce unnecessary height of navbar

---

pom.xml

For version 2.15.0 jackson-core is required to run.

Add missing jackson dependency

---

vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/batchRegistration/SampleSpreadsheetLayout.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/batchRegistration/SpreadsheetDropdownFactory.java

* locks whole spreadsheet (**this is the way** to do it)
* provides functionality to unlock specific columns
* unlocks dropdown column for NGS spreadsheet

lock spreadsheet, add unlock-method for columns

---

projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/BiologicalReplicate.java
projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalGroup.java
projectmanagement/src/test/groovy/life/qbic/projectmanagement/domain/project/experiment/BiologicalReplicateSpec.groovy

Generates unique biological replicate entities within an experimental group.

Generate biological replicates upon exp. group creation

---

vaadinfrontend/frontend/themes/datamanager/components/card.css
vaadinfrontend/frontend/themes/datamanager/components/custom.css
vaadinfrontend/src/main/java/life/qbic/datamanager/views/general/DisclaimerCard.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentalGroupCard.java

1.) Introduce dedicated component css stylings ("card.css"), which will host all the css to be used within the card component and it's extended variants 
2.) Refactor how the individual classes are called within the java classes and css

Base css styling definitions on the extended java component

---

vaadinfrontend/frontend/themes/datamanager/components/card.css
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentInfoComponent.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentInfoEditEvent.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentalVariablesComponent.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentalVariablesEditEvent.java

Add experimental variables component

---

vaadinfrontend/frontend/themes/datamanager/components/custom.css
vaadinfrontend/frontend/themes/datamanager/components/page-area.css
vaadinfrontend/frontend/themes/datamanager/components/vaadin-button.css
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/ProjectNavigationBarComponent.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/ExperimentInformationMain.java

Improve navigation bar [affordance](https://uxplanet.org/ux-design-glossary-how-to-use-affordances-in-user-interfaces-393c8e9686e4) through: 
1.) Elevation for navigation buttons
2.) Cursor change on mouseover for all buttons to pointer
3.) Disable Buttons without Route
**Before:**
**After**

Elevate navigation buttons and change mouseover cursor to pointer for all buttons

---

vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/SampleRegistrationSpreadsheet.java

* Hides standard letter and digit header and row ids of the spreadsheet
* Creates custom column (by adding "ROW" to header Enums) that shows a bold enumeration in the (currently) leftmost column
* Fixes an issue where columns that had pre-filled data were editable before and - in some cases - after validation
* Removes some methods used to figure out which columns should be editable - replaces them by a method that decides by the header of that column
* Renames some methods to better reflect their functionality

Display numbers of samples to create in custom column

---

projectmanagement/src/main/java/life/qbic/projectmanagement/application/sample/SampleInformationService.java

The filter lead to a mismatch of count and returned list length in the vaadin callback dataprovider.

Fix sample page not loading

---

vaadinfrontend/frontend/themes/datamanager/components/custom.css
vaadinfrontend/frontend/themes/datamanager/components/icon.css
vaadinfrontend/frontend/themes/datamanager/components/span.css
vaadinfrontend/frontend/themes/datamanager/components/vaadin-custom.css
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/ExperimentListComponent.java

1.) Add Flask icon to experimentItem 
2.) Update css to set font-size and padding according to figma prototype
3.) Sort items in experimentList properly by experimentName, ignoring case of item.

Add flask icon to experimentList item and update style

---

vaadinfrontend/frontend/themes/datamanager/components/custom.css
vaadinfrontend/frontend/themes/datamanager/components/info.css
vaadinfrontend/frontend/themes/datamanager/components/main.css
vaadinfrontend/frontend/themes/datamanager/components/page-area.css
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/info/InformationComponent.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectDetailsComponent.java

Provides substantial refactoring for the project summary, increasing readability while also introducing a new UI change.
The project information now displays information in sections with funding information.

Introduce sections for the project summary

---

projectmanagement/src/main/java/life/qbic/projectmanagement/application/ProjectCreationService.java
projectmanagement/src/main/java/life/qbic/projectmanagement/application/ProjectInformationService.java
projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/Funding.java
projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/Project.java
projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/service/ProjectDomainService.java
projectmanagement/src/test/groovy/life/qbic/projectmanagement/application/ProjectCreationServiceSpec.groovy
vaadinfrontend/frontend/themes/datamanager/components/dialog.css
vaadinfrontend/src/main/java/life/qbic/datamanager/views/general/funding/FundingEntry.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/general/funding/FundingField.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/ProjectFormLayout.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/edit/EditProjectInformationDialog.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/overview/ProjectOverviewPage.java
vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectDetailsComponent.java
vaadinfrontend/src/main/resources/application.properties

A new custom field for funding information is introduced to provide grant information, which enriches the available project information to store.

Introduce funding section to provide project grant information

---

vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectDetailsComponent.java

1.) Remove outdated fields and code 
2.) Remove duplicate tags in project view if same analyte, species, specimen were set in multiple experiments

Remove duplicated tags in projectview due to same analyte, specimen, species in multiple experiments

---

project-management/src/main/java/life/qbic/projectmanagement/domain/model/experiment/Experiment.java

This PR fixes the column creation for the experiment table.

Fixes JPA experiment column creation 

---

user-interface/src/main/java/life/qbic/datamanager/views/account/AccessTokenDeletionConfirmationNotification.java
user-interface/src/main/java/life/qbic/datamanager/views/account/PersonalAccessTokenMain.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectInformationMain.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/BatchDeletionConfirmationNotification.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/purchase/PurchaseItemDeletionConfirmationNotification.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/qualityControl/QCItemDeletionConfirmationNotification.java

Adds a notification asking users to confirm deletion of the following items:
* Personal Access Tokens
* Offers
* QC Files

Ask for confirmation on delete of several items

---

project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/project/ProjectRepositoryImpl.java
user-interface/src/main/java/life/qbic/datamanager/security/UserPermissionsImpl.java
user-interface/src/main/java/life/qbic/datamanager/views/navigation/ProjectSideNavigationComponent.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/ProjectMainLayout.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/ExperimentMainLayout.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/info/QualityControlListComponent.java

* allows users access to the "Project Access Management" page for projects they have created
* they can add or remove other users
* other users can edit the respective projects, but cannot access the "Project Access Management" page themselves

allow users to edit access to their projects

---

user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java

* Adds a comparator that can handle Strings containing numbers and sorts in a humanly intuitive way, e.g.: group1 < group2 < group11
* Applies that sorting for group and variable names in the experimental design page

better sorting for groups and variables

---

user-interface/src/main/java/life/qbic/datamanager/views/account/PersonalAccessTokenComponent.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/rawdata/RawDataDownloadInformationComponent.java

Provide linkage to our download documentation hosted on github pages

Update download instructions to current documentation

---

user-interface/frontend/themes/datamanager/components/page-area.css
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementDetailsComponent.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/rawdata/RawDataDetailsComponent.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/BatchDetailsComponent.java

Remove View button from BatchDetails component
Swap Sample Label and Code as requested

Minor UI updates

---

project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/project/ProjectRepositoryImpl.java

Ensures proper transactional roleback on failed datasource task

---

project-management/src/main/java/life/qbic/projectmanagement/domain/model/project/ProjectIntent.java
project-management/src/main/java/life/qbic/projectmanagement/domain/model/project/ProjectObjective.java

Increase objective length

---

user-interface/src/main/java/life/qbic/datamanager/views/general/HasBinderValidation.java
user-interface/src/main/java/life/qbic/datamanager/views/general/contact/AutocompleteContactField.java

Removes error text duplication.

Remove duplicate error message

---

user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/BatchRegistrationDialog.java

(cherry picked from commit 3b0718956e64a2d3fd9888a0c9c7420eda3bcb18)

Add a prefill row for every replicate in an experimental group. (#633)

---

user-interface/src/main/java/life/qbic/datamanager/views/general/HasBinderValidation.java
user-interface/src/main/java/life/qbic/datamanager/views/general/contact/AutocompleteContactField.java

(cherry picked from commit 6af5380363f99c8d00f5ef9a190dd77e8f006b10)

Remove duplicate error message (#631)

---

user-interface/frontend/themes/datamanager/components/vaadin-custom.css
user-interface/src/main/java/life/qbic/datamanager/views/projects/create/OntologyComboboxFactory.java

* remove chevron from ontology search boxes
* reformulate placeholder/helper text so users know it's not a dropdown

improve UX for ontology search

---

user-interface/src/main/java/life/qbic/datamanager/views/identicon/IdenticonGenerator.java

Makes Shraddha really happy :)

Fix colour range of identicons to a sensitive palette

---

user-interface/src/main/java/life/qbic/datamanager/Application.java
user-interface/src/main/resources/META-INF/additional-spring-configuration-metadata.json
user-interface/src/main/resources/application.properties

Introduces application properties to enable session and cookie management via environment variables and specifies push mode to long polling in data manager application.

Introduce http session expiration to enable rolling deployment in HA setting

---

user-interface/src/main/java/life/qbic/datamanager/Application.java
user-interface/src/main/resources/META-INF/additional-spring-configuration-metadata.json
user-interface/src/main/resources/application.properties

Exactly the same as #697, however had to be reverted and reopened due to not giving proper attribution to @sven1103

 Introduce http session expiration to enable rolling deployment in HA setting

---

user-interface/src/main/java/life/qbic/datamanager/views/account/PersonalAccessTokenComponent.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/rawdata/RawDataDownloadInformationComponent.java

Update Documentation URL and cURL command

Update documenation for raw data download

---

CODE_OF_CONDUCT.md

To provide a framework of interaction within our projects, we need a code of conduct.
I used the Github template for this, since imo this is sufficient for our projects.

Provide code of conduct

---

user-interface/frontend/themes/datamanager/components/div.css
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/rawdata/RawDataMain.java

Link to documentation in empty Raw Data view

---

README.md

Lets get the ratings up and the smell down

Adds sonar cloud info badges

---

project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/sample/openbis/OpenbisConnector.java

The openbis api only specifies a List but expects a mutable List.

Fix issue with sample creation

---

user-interface/src/main/java/life/qbic/datamanager/views/projects/overview/ProjectOverviewMain.java
user-interface/src/main/resources/messages/toast-notifications.properties

Displays a success toast for successful project creation, or error toasts for failing project or experiment tasks.

Display toasts in case of project creation

---

project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectServiceImpl.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectSummaryComponent.java

Provides the API to handle more project information tasks.

Add API objects for project information

---

project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java

Adds the missing API docs for project creation.

Add missing API docs

---

project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectServiceImpl.java
project-management/src/main/java/life/qbic/projectmanagement/domain/model/OntologyTerm.java
project-management/src/test/groovy/life/qbic/projectmanagement/application/api/AsyncProjectServiceImplTest.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectSummaryComponent.java

Implements the reactive API for querying experimental information.
Wires the async service call in the UI and renders information about species, specimen and analyte dynamically.

Implement experiment query API

---

service_api.md

Provides some class diagrams to provide an overview of the service API structure.

Add service api documentation

---

project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectServiceImpl.java

This pull request introduces a new API for managing experimental groups.

Add API for experimental group management

---

project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectServiceImpl.java
project-management/src/main/java/life/qbic/projectmanagement/application/measurement/MeasurementService.java
user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementMain.java
user-interface/src/main/resources/messages/toast-notifications.properties

Enables the registration of measurements for proteomics.

Extend registration for proteomics measurement

---

project-management/src/main/java/life/qbic/projectmanagement/application/ProjectInformationService.java

Catches the correct lock exception and triggers retry.

Correct locking exception handling
