qbicsoftware/data-manager-app

- webapp/src/main/java/life/qbic/views/components/InformationMessage.java
- webapp/src/main/java/life/qbic/views/components/SuccessMessage.java
- webapp/src/main/java/life/qbic/views/login/LoginHandler.java
- webapp/src/main/java/life/qbic/views/login/LoginLayout.java
- webapp/src/main/java/life/qbic/views/register/UserRegistrationLayout.java
Replaces the wrongly titled successmessage with an information message used for email confirmation. 
Additionally introduces a correctly styled SuccessMessage. 
Style adheres to the notification prototypes in [Figma](https://www.figma.com/file/mYcW5viu5GpPZ852VHYBrV/Start-Page?node-id=0%3A1) 
Demo of the new Notifications:
> Introduce correctly styled successMessage and informationMessage

- core/pom.xml
- core/src/test/groovy/life/qbic/domain/user/UserSpec.groovy
- core/src/test/groovy/life/qbic/domain/usermanagement/registration/RegistrationSpec.groovy
- core/src/test/groovy/life/qbic/domain/usermanagement/repository/UserRepositorySpec.groovy
- pom.xml
- webapp/pom.xml
- webapp/src/main/java/life/qbic/usermanagement/passwordreset/PasswordResetLinkSupplier.java
- webapp/src/main/java/life/qbic/usermanagement/registration/EmailConfirmationLinkSupplier.java
- webapp/src/main/resources/application.properties
- webapp/src/test/groovy/life/qbic/events/DomainEventSerializerSpec.groovy
- webapp/src/test/groovy/life/qbic/events/EventStoreSpec.groovy
- webapp/src/test/groovy/life/qbic/usermanagement/passwordreset/PasswordResetLinkSupplierSpec.groovy
- webapp/src/test/groovy/life/qbic/usermanagement/registration/EmailConfirmationLinkSupplierSpec.groovy
Introduces a configurable URL protocol parameter, that
can be used to set the protocol to http/https for URLs
that are send via email for user interaction.
> Add URL protocol to generated links

- webapp/src/main/java/life/qbic/views/login/LoginHandler.java
- webapp/src/main/java/life/qbic/views/login/LoginLayout.java
- webapp/src/main/java/life/qbic/views/register/UserRegistrationHandler.java
- webapp/src/main/java/life/qbic/views/register/UserRegistrationLayout.java
**Purpose of this PR**
This PR moves the notification Logic from the loginlayout and registrationlayout to their respective handler.
Additionally it cleans up the initlayout method by introducing dedicated methods to create and style the individual components.
> Move Notification Logic from each Layout to their respective Handler

- webapp/frontend/generated/vaadin.ts
- webapp/src/main/java/life/qbic/security/UserDetailsServiceImpl.java
- webapp/src/main/java/life/qbic/views/helloworld/HelloWorldView.java
- webapp/src/main/java/life/qbic/views/login/LoginHandler.java
Introduces a default route `@Route("")`, which is the hello page for the moment.
Since none was defined previously, this led to undesired side effects, causing Vaadin Router not to be able to resolve the default route.
In addition, I found my chance a leaking exception into the log, which happens when you enter a non-valid email address on login (not an email address for example). It is fixed by catching the EmailValidationException.
> Set the hello world view as default route

- .gitignore
- core/src/main/java/life/qbic/identityaccess/application/user/PasswordResetOutput.java
- core/src/main/java/life/qbic/identityaccess/application/user/PasswordResetRequest.java
- core/src/main/java/life/qbic/identityaccess/application/user/UserRegistrationService.java
- core/src/main/java/life/qbic/identityaccess/domain/user/EmailAddress.java
- webapp/src/main/java/life/qbic/views/components/BoxLayout.java
- webapp/src/main/java/life/qbic/views/login/passwordreset/PasswordResetHandler.java
**Purpose of this PR**
This PR introduces an error notification shown to the user if the password reset fails
**How to Test**
In the Password Reset View, input an email address not stored in the database and click the submit button. 
The Password Reset
**Possible Improvements**
The Handler could try to distinct between a password reset failure caused by a domain error a passwort reset failure caused by an invalid email input reset. 
To do so we would need to introduce a dedicated PasswortResetException similiar to the UserRegistrationException which can then be parsed from the ApplicationResponse via the output interface to the Handler
> Introduce error notification for failure of password reset 

- .github/workflows/create-release.yml
**What has changed**
Adds the deploy goal to mvn lifecycle deploy phase. 
If only a phase is defined, then all the phases before that phase will be redone repackaging our artifact without the specified profile.
**Additional information**
Information about maven lifecycles can be found [here:](https://baeldung-cn.com/maven-goals-phases)
> Avoid artifact repackaging during deployment of release workflow

- .github/workflows/create-release.yml
**Purpose of this PR**
Addresses [failure in release build](https://github.com/qbicsoftware/data-manager-app/runs/7519905215?check_suite_focus=true).
Add `jar:jar` goal to the deploy stage in create release github workflow to initialize the deployment requirements. 
**Additional information**
Basically the `deploy:deploy` goal needs to know, which file and filetype should be deployed. 
Originally this would be done by the previous lifecycles(e.g. mvn install), however this is not possible since the CI is packaging the artifact and then deploying it seperately. 
We can force the correct initialization by adding the `jar:jar goal` which will prepare everything for building the jar(ergo preparing the necessary deployment settings), however since we already build the jar it will not be …
> Add jar initialization to prepare deployment in create release workflow

- commons/src/main/java/life/qbic/application/commons/ApplicationResponse.java
Opens the ApplicationResponse.Type enum, since it is a return type of the public API.
> Open field access for public response type

- authentication/pom.xml
- logging/pom.xml
- subscription-provider/pom.xml
- subscription-provider/src/main/java/life/qbic/logging/subscription/provider/mail/EMailService.java
- subscription-provider/src/main/resources/META-INF/services/life.qbic.logging.subscription.api.Subscriber
- vaadinfrontend/pom.xml
- vaadinfrontend/src/main/java/life/qbic/datamanager/Application.java
- vaadinfrontend/src/main/resources/application.properties
After the removal of Java modules support, the Subscription provider implementation broke. 
This enables the findability of the service via the legacy `META-INF/services` approach to expose service providers.
> Fixes Subscription service provider 

- vaadinfrontend/frontend/styles/components/card-layout.css
- vaadinfrontend/frontend/styles/components/create-project.css
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/components/CardLayout.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/CreateProjectLayout.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projectOverview/components/CreationModeDialog.java
This PR updates the UI to fit the [figma ](https://www.figma.com/file/mYcW5viu5GpPZ852VHYBrV/Start-Page?node-id=861%3A20351)prototype outlined in [DM-530](https://qbicsoftware.atlassian.net/browse/DM-530).
**Technical Information** 
This PR aims to achieve multiple things: 
1.) Introduce a reusable CardLayout with an immutable card design
2.) The CardLayout allows for adding components into its individual sublayouts as desired by the user. 
3.) The CardLayout allows for style changes to its Sublayouts as required. 
4.) CSS definition seperation between the basic CardLayout and the styling of the added components by the CreateProjectLayout
**How to Test**  
1.) Login to the data-manager-app
2.) Click the Create Button on the top left
3.) Click the "blank" button in …
> Update design of Create Project UI

- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/ProjectInformationDialog.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/overview/components/ProjectOverviewComponent.java
Addresses [DM-572 ](https://qbicsoftware.atlassian.net/browse/DM-572) by allowing the Reset functionality to also reset textfield state (Remove invalid marker and highlighting) in the projectinformation dialogue window. 
Additionally the reset is triggered independent on how the dialogue window is closed
> Reset functionality also resets textfield state

- finances/src/main/java/life/qbic/projectmanagement/domain/finances/offer/ExperimentalDesignDescription.java
- finances/src/main/java/life/qbic/projectmanagement/domain/finances/offer/Offer.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/application/ProjectCreationService.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/ExperimentalDesignDescription.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/Project.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/ProjectIntent.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/ProjectInformationDialog.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/overview/components/ProjectOverviewComponent.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/view/components/ProjectDetailsComponent.java
- vaadinfrontend/src/main/resources/messages.properties
Removes the optional wrapping of the experimentaldesigndescription in the domain and application logic since it's a mandatory field now. 
**Additional changes**
Also updated the database by filling in the empty experimental design fields for all currently created projects. 
**More Information**
Addresses DM-635
> Make experimental design required during project creation and update

- projectmanagement/src/main/java/life/qbic/projectmanagement/application/ProjectCreationService.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/application/ProjectInformationService.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/Project.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/create/ProjectInformationDialog.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/overview/components/ProjectOverviewComponent.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/view/components/ProjectDetailsComponent.java
Adds the possibility to optionally add a responsible person during the project creation and update process
**Nice to know** 
Vaadin 23 flow does not provide the possiblity of empty selection during selection in the combobox component. 
The current workaround uses the clear button provided by the combobox to allow empty selection after a responsible person was specified
**Details**
Ordering and implementation according to prototype: [DM-655](https://qbicsoftware.atlassian.net/browse/DM-655)
Added a new column to store the responsible person information in the `project_datamanager` table called `responsiblePersonDef`
[DM-655]: https://qbicsoftware.atlassian.net/browse/DM-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow specification for responsible person during project creation and project update

- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/view/components/ProjectDetailsComponent.java
Adjusts the width of the multiselect-comboboxes to stay within the boundaries of the outer projectdetailscomponent.
**Why it was changed**
Because the Viewpoint width was set to high, the projectdetailscomponent got pushed outside of the right side of the screen
> Fix Spacing of ProjectDetailsComponent

- database-connector/src/main/java/life/qbic/projectmanagement/persistence/repository/OpenbisConnector.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/AppRoutes.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/MainLayout.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/login/LoginHandler.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/project/overview/ProjectOverviewPage.java
A parent layout should not be the root route, since tthis will show the navigation page after login in development mode, and not work at all in production mode (route cannot be found!).
Every Vaadin App should have a defined root route, that represents the default entry page for a user.
> Set projects overview as root route

- vaadinfrontend/src/main/resources/application.properties
Removes the set property `vaadin.productionMode=false` from the `application.properties `since it leads to a RuntimeException on qPylon since Vaadin 24.
> Hotfix 0.15.1

- vaadinfrontend/src/main/resources/messages_de.properties
Removes the messages_de.properties file which provides german translations for error messages. As vaadin currently only supplies the HTTPRequest with the server locale, this does not take effect and leads to confusion.
> Remove german exception messages as vaadin always uses machine not client locale

- projectmanagement/src/main/java/life/qbic/projectmanagement/application/policy/directive/AddSampleToBatch.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/application/policy/directive/CreateNewSampleStatisticsEntry.java
The RTE is necessary in the directive execution so we can use the
JobRunr scheduler to trigger its retry policy.
> Throw RTE if sample cannot be attached to a batch

- vaadinfrontend/src/main/resources/application.properties
If we want to run multiple instances of the `data-manager-application` e.g. one for user tests and one for development we need to be able to set the jobrunnr port via [environment variables](https://www.jobrunr.io/en/documentation/configuration/spring/). 
Otherwise both instances will try to host jobrunr on the same time leading to an exception.
> Allow specification of Jobrunr port via application properties

- vaadinfrontend/frontend/themes/datamanager/components/card.css
Remove flex-grow and flex-shrink properties to keep experiment-variable fact-sheet size consistent:
**before**
**after**
> Keep experimental variable fact-sheet size consistent within experimental-variables collection

- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
Added oneliner for lumoutility since css selector is tricky within tabsheet
I'll look into it after the release again
**Before**
**After**
> Experimental Variables are shown next to the factsheet 

- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/SampleRegistrationSpreadsheet.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/SampleSpreadsheetLayout.java
The user is now unable to delete the final row(outside of the columnheaders) and is informed via a notification that this is not possible. 
**Technical Note**
I wanted to propagate the notification via an applicationexception within the layout, however this leads to the spreadsheet component breaking entirely, which is why a dedicated notification was necessary.
> Inform User that row deletion is not possible if only one row remains in the spreadsheet. 

- projectmanagement/src/main/java/life/qbic/projectmanagement/application/policy/SampleRegisteredPolicy.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/application/policy/directive/AddSampleToBatch.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/application/policy/directive/CreateNewSampleStatisticsEntry.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/application/sample/SampleRegistrationService.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/sample/Batch.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/sample/SampleId.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/SampleRegistrationSpreadsheet.java
As of now all the scheduled jobs in jobrunnr for the batch registration were not working properly. 
(Check failed jobs on your local jobrunr instance) 
This PR ensures that the sampleIds are loaded properly before the batch is registered and fixes the database schema between sampleIds and batchIds. 
Also it fixes a minor issue in the spreadsheet if only one biological replicate is in the experiment. 
Finally the jobs now have a proper naming schema to make debugging easier
> Batch registration is enqueued propely with jobrunnr

- database-connector/src/main/java/life/qbic/projectmanagement/experiment/persistence/SampleStatisticEntry.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/application/sample/SampleInformationService.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalGroup.java
- projectmanagement/src/main/java/life/qbic/projectmanagement/domain/project/experiment/ExperimentalVariable.java
1.) The GenerationType strategy for the ids within experimental variable and experimental groups should be set to Auto so it's incremented correctly. Otherwise the generation of a new group/variable will fail since there is no default value provided 
2.) Remove unnecessary postfiler on samplePreview query since there are no permissions implemented yet
> Set Generationtype strategy to AUTO for id generation

- vaadinfrontend/frontend/themes/datamanager/components/dialog.css
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/BatchRegistrationDialog.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/SampleRegistrationSpreadsheet.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/SampleSpreadsheetLayout.java
This PR achieves two things:
1.) Adapt styling so the dialog buttons are always visible in the spreadsheetlayout 
2.) Ensure the spreadsheet is prefilled correctly(or not prefilled) and streamline reload logic in spreadsheetlayout
**How to Test**
1.) Select "My new Experiment" in "SampleRegistrationSheeTtester" project on smaller screen size on qpylon and locally and try to see if the buttons are shown. 
2.) Select "Experiment 0" in "SampleRegistrationSheeTtester" project and observe "orphaned" entries in replicate column of the spreadsheet even if prefill was not selected:
> User can see the button in the spreadsheet layout independent of number of rows

- .gitignore
- vaadinfrontend/frontend/themes/datamanager/components/page-area.css
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
* removes species, specimen, analyte tags from the top of the experiment page
* adds default tag as an example, until notes are correctly implemented
* implements new display of species, specimen and analytes below the tags
> Redesign experiment summary

- vaadinfrontend/frontend/themes/datamanager/components/dialog.css
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentalGroupsDialog.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentalVariablesDialog.java
* remove one of the two titles in the add variable dialog
* style adding of variables like in add-group dialog
* if the last variable row is removed in "add mode" (as opposed to edit mode), a new empty row is automatically added
* remove some unnecessary CSS
> align add-variable dialog with UI of add-group dialog

- vaadinfrontend/frontend/themes/datamanager/components/main.css
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectInformationMain.java
Since we are going to introduce a different navigation scheme soon, the navbar is obsolete in the project information page, since the progress is only relevant on experiment level.
> Remove navigation bar from project information page

- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleDetailsComponent.java
- vaadinfrontend/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/BatchRegistrationDialog.java
Hotfix to ensure dialog is reset properly after samples have been registered correctly
> Reset dialog upon batch registration

- database-connector/src/main/java/life/qbic/projectmanagement/persistence/repository/OpenbisConnector.java
The openBIS sample entry will now contain the sample entity unique ID as reference to the data manager.
Moreover, as secondary name the sample label will now be used instead of the biological replicate id.
> Reference unique sample id in openBIS

- vaadinfrontend/src/main/java/life/qbic/datamanager/views/navigation/ProjectSideNavigationComponent.java
Since the content div is static, it's not possible to add it to different state trees. Trying to do so leads to a Statetree exception. 
Therefore we need to make sure the content div is reset completely and not added multiple times to the parent container 
**How to reproduce** 
1.) Login to the application and select a project so the drawer is initialized
2.) Copy the URL into a different tab and load the page 
3.) Observe state tree exception since the application tries to add a static content div to multiple instances
> Reset appdrawer content correctly to avoid node tree exception

- project-management/pom.xml
- user-interface/pom.xml
Fix the following exception:
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'simpleOfferSearchService' for bean class [life.qbic.finance.persistence.SimpleOfferSearchService] conflicts with existing, non-compatible bean definition of same name and class [life.qbic.controlling.infrastructure.SimpleOfferSearchService]
> Removes former reference to the database connector

- project-management/src/main/java/life/qbic/projectmanagement/application/authorization/acl/ProjectAccessServiceImpl.java
Revoking access to a project is done via deleting the acl entries within a mutable acl object. However the current implementation leads to an indexing issue since we're deleting entries from a list that is not in sync with the copied aclEntries list. This can be avoided by starting the deletion and iteration from the highest number in the list.
> Address indexing error within acl deletion when user is removed from a project

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
After the routing update introduced with the experimentnavigation component, the hardcoded URL in the notification was no t working anymore. 
To futureproof this the String was replaced with the route retrieved from the class in question as suggested by the [vaadin docs](https://vaadin.com/docs/latest/routing/retrieving-routes)
> Ensure that notification anchor after group registration always points to SampleInformationMain

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/ontology/OntologyTermJpaRepository.java
- project-management/src/main/java/life/qbic/projectmanagement/application/OntologyTermInformationService.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/OntologyFilterConnector.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/create/ExperimentAddDialog.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/update/ExperimentUpdateDialog.java
* Do not show terms until user types at least two letters
* State this in helper text
* Return only 50 results per search to prevent scrolling lag
> Small UI and usability changes for ontology term selection

- project-management/src/main/java/life/qbic/projectmanagement/domain/model/experiment/vocabulary/OntologyClassDTO.java
- user-interface/frontend/themes/datamanager/components/div.css
- user-interface/src/main/java/life/qbic/datamanager/views/general/OntologyComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/OntologyFilterConnector.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/Tag.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectDetailsComponent.java
* renders OntologyComponent in dropdown menus using ontologies - this displays the name of the source ontology and the "name" (unique ID of the term)
* the same information is added as a tooltip for tags and spans used in experiment and project overview components
> display more info about ontology terms for experiments

- application-commons/src/main/java/life/qbic/application/commons/Result.java
- application-commons/src/test/groovy/life/qbic/application/commons/ErrorSpec.groovy
- application-commons/src/test/groovy/life/qbic/application/commons/ValueSpec.groovy
- user-interface/frontend/themes/datamanager/components/spreadsheet.css
- user-interface/src/main/java/life/qbic/datamanager/views/general/spreadsheet/Spreadsheet.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleContentComponent.java
**1.) Drag and drop within the cells of a spreadsheet is stuck when a comment is shown**
Seems to be related to the drawingpatriarch used in the vaadin spreadsheet. For now drag and drop is only possible if no cell comment pops up during drag and drop operations. Since this behaviour is finicky we remove the comments for now. 
**2.) The Spreadsheet rendering collapses if a notification is shown or closed**
Rendering the notification popup or closure leads to the breakage of the spreadsheet which would necessitate a complete refresh of all cells within the spreadsheet. Since this is not feasible for all possible notifications, the easier solution for now is to just close the dialog and show the notification afterwards. 
**ToDo**
Since the spreadsheet is a "gift" that …
> Remove cell comments and always close dialogue to address remaining spreadsheet issues

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/ExperimentListComponent.java
The add experiment button now fits the color scheme defined in the [prototype](https://www.figma.com/file/mYcW5viu5GpPZ852VHYBrV/Start-Page?type=design&node-id=4276-88806&mode=dev)
> Remove primary style of add button in experimentlistcomponent

- user-interface/frontend/themes/datamanager/components/dialog.css
- user-interface/frontend/themes/datamanager/components/div.css
- user-interface/src/main/java/life/qbic/datamanager/views/projects/create/CollaboratorsLayout.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/create/ExperimentalInformationLayout.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/create/FundingInformationLayout.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/create/ProjectDesignLayout.java
1.) Instead of dummy description texts, the layouts now show the descriptions defined in the figma prototype
2.) The header of the person responsible was renamed
3.) CSS style changes so the dialog is sized as intended 
**Prototype**
The figma prototype can be found [here](https://www.figma.com/file/mYcW5viu5GpPZ852VHYBrV/Start-Page?type=design&node-id=4788-99390&mode=dev)
> Project creation dialog shows descriptions for each layout and adheres to sizing scheme for our dialogs

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/sample/QbicSampleDataRepo.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/sample/SampleRepositoryImpl.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/sample/openbis/OpenbisConnector.java
- project-management/src/main/java/life/qbic/projectmanagement/application/DeletionService.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/repository/SampleRepository.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/service/SampleDomainService.java
- user-interface/src/main/java/life/qbic/datamanager/views/general/spreadsheet/Spreadsheet.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleContentComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/EditBatchDialog.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/SampleBatchInformationSpreadsheet.java
Pressing the **remove row** button in the **edit batch** dialog to remove samples now sends an event that checks if samples can be removed (or if data is attached).
If users are not allowed to remove that sample, the spreadsheet is used to inform the user about this, similar to other validation errors.
This fixes the issue that a notification popup would break the spreadsheet UI.
Removing samples outside of the spreadsheet context (deleting the whole batch) will still show the respective notification.
> Fix spreadsheet breaking on deletion request

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/sample/openbis/OpenbisConnector.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/sample/AnalysisMethod.java
* Fixes and enables sample metadata update in openBIS, which was caused by an immutable list
* Fixes project search in openBIS, which was not searching for the project code
* Fixes a typo in Analysis Type
> Fix sample editing and project search in openBIS

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/OntologyFilterConnector.java
* queries to the ontology database (via filter input) now return a list of unique values, fixing an issue with the displayed components
* this is only an additional safeguard, as duplicates will be removed from the table and the scripts to fill the table adapted
See also: https://github.com/qbicsoftware/dm-onthology-terms/pull/2
> only load unique ontology terms

- project-management/src/main/java/life/qbic/projectmanagement/application/batch/SampleUpdateRequest.java
- project-management/src/main/java/life/qbic/projectmanagement/application/sample/SamplePreview.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/sample/Sample.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/sample/SampleRegistrationRequest.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/service/SampleDomainService.java
- project-management/src/test/groovy/life/qbic/projectmanagement/application/SampleRegistrationServiceSpec.groovy
- project-management/src/test/groovy/life/qbic/projectmanagement/domain/service/SampleDomainServiceSpec.groovy
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleContentComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/SampleBatchInformationSpreadsheet.java
(fixes typo in original branch name)
Adds the property 'Organism Id' to Sample objects, Sample creation and Sample editing.
This optional property allows to discriminate between samples that are from the same patient or model organism and samples that are from different individuals.
Since the property is optional, these changes are backwards compatible and older batches/samples can still be displayed/edited. However, the following column has to be added to the **sample** table:
`organism_id varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL`
> add optional sample property 'organism id'

- project-management/src/main/java/life/qbic/projectmanagement/application/DeletionService.java
- project-management/src/main/java/life/qbic/projectmanagement/application/batch/BatchRegistrationService.java
- project-management/src/main/java/life/qbic/projectmanagement/application/policy/SampleDeletedPolicy.java
- project-management/src/main/java/life/qbic/projectmanagement/application/policy/directive/DeleteSampleFromBatch.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/batch/Batch.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/sample/event/SampleDeleted.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/service/SampleDomainService.java
- project-management/src/test/groovy/life/qbic/projectmanagement/application/policy/SampleDeletedPolicySpec.groovy
- user-interface/frontend/themes/datamanager/components/div.css
- user-interface/src/main/java/life/qbic/datamanager/AppConfig.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/BatchDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleContentComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleDetailsComponent.java
This PR introduces the logic to show and adjust the number of samples, the modification date and creation date for a batch in the batchgrid. 
**Technical Issues**
1.) To show the correct number of samples after a batch editing has taken place, a seperate "SampleDeletion" domain event has to be published and consumed as a job by jobrunr correctly.
This works locally, however if the job event is taken by qpylon then the job can't be run since the necessary methods are only implemented in this branch
2.) Because of the "lag" introduced through the job consumption via jobrunr during sample deletion or creation, the sample number is only adjusted if the page is reloaded after the job has run in jobrunr successfully.
> Show number of samples, creation- and modificationdate in batchdetailscomponent

- user-interface/frontend/themes/datamanager/components/div.css
- user-interface/frontend/themes/datamanager/components/page-area.css
- user-interface/frontend/themes/datamanager/components/span.css
- user-interface/frontend/themes/datamanager/components/vaadin-custom.css
- user-interface/src/main/java/life/qbic/datamanager/views/general/OntologyComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
1.) Render Species, Specimen and Analyte List in ExperimentDetailsComponent according to [prototype](https://www.figma.com/file/mYcW5viu5GpPZ852VHYBrV/Start-Page?type=design&node-id=6300-15816&mode=dev) with linkage to ClassIri of the selected onthology
A) Before:
B) New Design:
2.) Render Items within Multiselectcombobox according to [protoype](https://www.figma.com/file/mYcW5viu5GpPZ852VHYBrV/Start-Page?type=design&node-id=4788-99390&mode=dev) with correct formatting and layout:
A) Before:
B) New Design:
3.) Sort the css classes within the touched files alphabetically
4.) Remove the unused components within the ExperimentDetailsComponent (Note taking Textfield and "Space for Tags" Span)
> Highlight and provide Linkage to Onthology Class Iri

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentalGroupInput.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentalGroupsDialog.java
* Introduces the possibility to create an ExperimentalGroupsDialog with existing groups that cannot be edited
* This makes it easier for users to add unique experimental groups (not accidentally adding the same again)
* For the Add Groups use case, only new groups are returned
* For the Edit Groups use case, everything is returned as before, as all parts of the dialog are in "enabled" mode
> Show existing groups in add dialog

- identity/src/main/java/life/qbic/identity/application/token/PersonalAccessTokenServiceImpl.java
Currently the incorrect id is used to delete a token, leading to the deletion of the wrong token, since it's based on which token was fetched first from the backend (since they all have the same userId)
> Delete pat by tokenId instead of userId

- finances-infrastructure/pom.xml
- finances-infrastructure/src/main/java/life/qbic/finance/infrastructure/SimpleOfferSearchService.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/project/ProjectRepositoryImpl.java
- user-interface/pom.xml
- user-interface/src/main/java/life/qbic/datamanager/security/UserPermissionsImpl.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/create/AddProjectDialog.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/create/ProjectDesignLayout.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/overview/ProjectOverviewMain.java
* when adding a project, only adds offer search field to the interface if the user has admin or project_manager role
* disables search methods for offers for normal users (maybe unnecessary?)
> hide offer search from anyone but admin and project-manager

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/experiment/measurement/MeasurementLookupImplementation.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/experiment/measurement/MeasurementRepositoryImplementation.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/experiment/measurement/NGSMeasurementJpaRepo.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/experiment/measurement/ProteomicsMeasurementJpaRepo.java
- project-management/src/main/java/life/qbic/projectmanagement/application/measurement/MeasurementLookup.java
- project-management/src/main/java/life/qbic/projectmanagement/application/measurement/MeasurementLookupService.java
- project-management/src/main/java/life/qbic/projectmanagement/application/measurement/MeasurementService.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/NGSMeasurement.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/ProteomicsMeasurement.java
- user-interface/frontend/themes/datamanager/components/icon.css
- user-interface/frontend/themes/datamanager/components/main.css
- user-interface/frontend/themes/datamanager/components/page-area.css
- user-interface/frontend/themes/datamanager/components/span.css
- user-interface/src/main/java/life/qbic/datamanager/views/general/InfoBox.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementMain.java
This PR provides a UI implementation for showing the measurement data with lazy loading.
**ToDo**
1.) Decide on the properties to be filtered 
2.) Introduce frontend records hosting these properties to avoid leaking "entity" information
3.) Update Measurement validation in uploadDialog
**How to test**
A) Go to a measurement page without registered measurements --> disclaimer is shown
B) Go to the measurement main component for project `3997943c-4a08-4990-8df9-312230118445` and its experiment `68e55d0f-053e-4ac1-a346-2e4edc73e0aa` to see the registered proteomics measurements
> Feature/dm 407 provide UI for sample measurement information

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/batch/BatchJpaRepository.java
- project-management/pom.xml
- project-management/src/main/java/life/qbic/projectmanagement/application/batch/BatchRegistrationService.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/batch/Batch.java
The current implementation allowed JobRunner processes to concurrently load batch entities upon the AddSampleToBatch directive execution.
However, this lead to unwanted side-effects, resulting in batch information with corrupted state. The samples connected to the batch were random after every batch registration.
The reason for this side-effect is the concurrent loading and manipulation of the batch entity. Multiple processes are competing to read and update the sample batch with the sample id they are assigned to add. 
Since this is a classical race condition on data base level, we enable optimistic locking for the batch update transaction.
> Enable optimistic locking for concurrent sample batch updates

- identity-api/src/main/java/life/qbic/identity/api/UserInfo.java
- identity-api/src/main/java/life/qbic/identity/api/UserInformationService.java
- identity-infrastructure/src/main/java/life/qbic/identity/infrastructure/QbicUserRepo.java
- identity-infrastructure/src/main/java/life/qbic/identity/infrastructure/UserJpaRepository.java
- identity/src/main/java/life/qbic/identity/application/service/BasicUserInformationService.java
- identity/src/main/java/life/qbic/identity/application/user/IdentityService.java
- identity/src/main/java/life/qbic/identity/application/user/registration/RegisterUserInput.java
- identity/src/main/java/life/qbic/identity/application/user/registration/Registration.java
- identity/src/main/java/life/qbic/identity/application/user/registration/UserRegistrationException.java
- identity/src/main/java/life/qbic/identity/domain/model/User.java
- identity/src/main/java/life/qbic/identity/domain/repository/UserDataStorage.java
- identity/src/main/java/life/qbic/identity/domain/repository/UserRepository.java
- identity/src/main/java/life/qbic/identity/domain/service/UserDomainService.java
- identity/src/test/groovy/life/qbic/identity/domain/user/UserSpec.groovy
- identity/src/test/groovy/life/qbic/identity/domain/usermanagement/registration/RegistrationSpec.groovy
- identity/src/test/groovy/life/qbic/identity/domain/usermanagement/repository/UserRepositorySpec.groovy
- user-interface/src/main/java/life/qbic/datamanager/views/register/UserRegistrationHandler.java
- user-interface/src/main/java/life/qbic/datamanager/views/register/UserRegistrationLayout.java
This PR introduces the concept of usernames.
If a username already is in use, the user is getting the notification that they have to chose another one.
> Enable username for new user registrations

- project-management/src/main/java/life/qbic/projectmanagement/application/ProjectCreationService.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/service/ProjectDomainService.java
- project-management/src/test/groovy/life/qbic/projectmanagement/application/ProjectCreationServiceSpec.groovy
Handle duplicate project exception in domain service and propagate the error message to the user in application service
> Propagate to user if a project with the provided code already exists during project creation

- project-management/src/main/java/life/qbic/projectmanagement/domain/model/measurement/ProteomicsMeasurement.java
On our test system, the registration of measurements currently fails.
Since in a development feature branch, the new column fraction was introduced, we need to provide a default value for it.
> Provide default value for fraction

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/ontology/OntologyTermRepository.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/ontology/OntologyTermRepositoryJpaInterface.java
- project-management-infrastructure/src/test/groovy/life/qbic/projectmanagement/infrastructure/ontology/OntologyTermRepositorySpec.groovy
The query is omptimzed, such that we introduce a relevancy ranking based on a series of ranked expressions in the boolean mode query.
We also rank complete genus and species name now highest, so that complete class name entries will result as first hit result.
> Optimise ontology query

- project-management/src/main/java/life/qbic/projectmanagement/application/ontology/OntologyClass.java
- project-management/src/main/java/life/qbic/projectmanagement/application/ontology/OntologyLookupService.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/ontology/OntologyLookupComponent.java
* changes equals/hashcode methods of OntologyClass to only check classIRI (as it's unique!)
* makes list of hits returned by ontology search distinct
> Remove duplicate hits in ontology search

- project-management/src/main/java/life/qbic/projectmanagement/application/ExperimentInformationService.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/experiment/Condition.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentalGroupInput.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentalGroupsDialog.java
* Fixes issue where adding experimental groups would delete and recreate old groups
* Allows users to add (**not edit**) experiment groups, even if samples are already registered
> Allow to add new groups even if samples are registered

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExperimentalGroupsDialog.java
Fixes an issue where the test for incomplete groups - those without all defined variables - would not be checked upon edit or creation of groups
> Only allow creation of complete experimental groups

- user-interface/pom.xml
- user-interface/src/main/java/life/qbic/datamanager/CacheLogger.java
- user-interface/src/main/java/life/qbic/datamanager/security/AclSecurityConfiguration.java
- user-interface/src/main/resources/ehcache3.xml
Previously, the cache was not active and therefore we did not make actual use of the perfomance boost of cached ACL queries, which is especially helpful when users are navigating within the same project.
This PR enables the cache and also introduces a cache logger for debugging purposes.
> Enable ACL cache

- application-commons/pom.xml
- application-commons/src/main/java/life/qbic/application/commons/ApplicationException.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/project/ProjectRepositoryImpl.java
- project-management/src/main/java/life/qbic/projectmanagement/application/authorization/acl/ProjectAccessServiceImpl.java
- user-interface/src/main/resources/messages.properties
Listing collaborators is now allowed with READ permission in a project.
Also, I adjusted the exception handling, such that for ACCESS DENIED, the user no gets a more expressive message instead of a general error message.
> Listing collaborators only requires READ role and more expressive access denied message

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/rawdata/RawDataMain.java
The wrong ID type has been passed to the ACL protected service method (experiment ID instead of project ID).
Thus the authorization always failed.
This PR passes the project ID to enable the correct access policy.
> Enable download of URL file

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementMetadataUploadDialog.java
Microsoft Excel currently only supports exports to CSV UTF-8 format (which we do not support), TSV in an unknown format (thank you Microsoft) and Unicode UTF-16.
The latter uses the tab character as separator, which is exactly what we want. 
This PR reads in any file content for measurement metadata assuming UTF-16, which contains UTF-8 and thus should work for the most symbols used currently in production environments.
> Provide UTF-16 support for measurement metadata

- project-management/src/main/java/life/qbic/projectmanagement/domain/model/project/purchase/Offer.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/sample/qualitycontrol/QualityControlUpload.java
Blob only stores 65,535 bytes.
Medium blob stores  16,777,215 bytes
long blob stores 4 GB
As offers are expected to be larger than 15,9MB we need a bigger type.
```
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table purchase_offer modify column file_content BLOB" via JDBC [Data truncation: Data too long for column 'file_content' at row 2]
at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:94)
at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:574)
at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlStrings(AbstractSchemaMigrator.java:514)
at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.migrateTable(AbstractSchem …
```
> Increase size of stored offers

- project-management/src/main/java/life/qbic/projectmanagement/application/ProjectOverview.java
The project overview entity idicated to JPA a confusing setup with a column and join table for an element collection on the same field. This does always throw exceptions when hibernate is trying to set up the database. Further the wrong '@Immutable` annotation was used.
> Fix Project Overview entity

- README.md
The logo is a registered trademark and the copyright belongs to the University itself.
> Extend license note for University of Tübingen logo

- project-management-infrastructure/src/test/groovy/life/qbic/projectmanagement/infrastructure/sample/SampleCodeJpaRepositorySpec.groovy
- project-management/src/main/java/life/qbic/projectmanagement/domain/model/project/ProjectCode.java
- project-management/src/test/groovy/life/qbic/projectmanagement/application/ProjectCreationServiceSpec.groovy
- project-management/src/test/groovy/life/qbic/projectmanagement/domain/ProjectCodeSpec.groovy
- user-interface/src/main/java/life/qbic/datamanager/views/projects/create/ProjectDesignLayout.java
The legacy project codes are of length 5, so the data manager should not create codes that might be confused with legacy codes.
The most simple solution also discussed with project management is to extend the prefix from "Q" to "Q2".
> Extending project code to avoid collisions with legacy QBiC project codes

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/ExperimentDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/SampleOriginType.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/components/ExistingSamplesPreventSampleOriginEdit.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/experiment/update/EditExperimentDialog.java
Tackles #683 
https://github.com/qbicsoftware/data-manager-app/assets/10232219/a40fbfa5-9e07-4a99-864c-7aa870e18087
> Restrict sample origin editing, if origin is used

- project-management/src/main/java/life/qbic/projectmanagement/application/DeletionService.java
This PR fixes a bug preventing sample batches from being deleted.
Previous to this PR an application context was queried but the variable was always `null`. 
This PR fixes the behaviour by introducing a self proxying using spring's lazy initialization.
> Fix sample batches could not be deleted

- user-interface/src/main/java/life/qbic/datamanager/views/projects/create/OntologyComboboxFactory.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/experiments/OntologyFilterConnector.java
Due to the improvement of the OntologyTerm comparison by considering equal terms when they have the same IRI, the combobox showed empty rows for a term that was referenced in more than two ontologies.
This contribution filters them out.
Also, an unused ontology term list is removed. The NCBI Taxon filtering happens in the SpeciesSearchService and should also not be knowledgable by the client.
> Fix redundant ontology terms that are actually the same

- user-interface/src/main/java/life/qbic/datamanager/templates/measurement/NGSMeasurementEditTemplate.java
- user-interface/src/main/java/life/qbic/datamanager/templates/measurement/NGSMeasurementRegisterTemplate.java
- user-interface/src/main/java/life/qbic/datamanager/templates/measurement/ProteomicsMeasurementEditTemplate.java
- user-interface/src/main/java/life/qbic/datamanager/templates/measurement/ProteomicsMeasurementRegisterTemplate.java
- user-interface/src/main/java/life/qbic/datamanager/templates/sample/SampleBatchRegistrationTemplate.java
- user-interface/src/main/java/life/qbic/datamanager/templates/sample/SampleBatchUpdateTemplate.java
Same Content as PR #976 but reopened from Main to apply it as a hotfix
Addresses #975, by restraining the helper box only to the header of the templates. This is done so users can easily drag and drop the values within the cells. 
**Open Questions**
1.) Should there be a highlight that there is a helper box hidden within the helper cell?
2.) There are header cells with links, which direct the user to their respective homepage (Organization to RoR Homepage, Instrument to Ontology). Is this an issue if the user is solely interested in the helper box content?
> Show helper box only in the header cells of all sample and measurement excel templates

- project-management/src/main/java/life/qbic/projectmanagement/application/measurement/MeasurementService.java
Uses the external TIB terminology service to look up ontologies for instruments.
> Use TIB terminology service for instrument lookup

- user-interface/src/main/resources/application.properties
The address of the service API changed.
See https://api.terminology.tib.eu/swagger-ui/index.html#/ for more information.
> Update default values for the TIB environment variables

- project-management/src/main/java/life/qbic/projectmanagement/domain/model/batch/Batch.java
Ensures that sample IDs already referenced in the sample batch are not added again, which led to duplicates.
> Batch update must be idempotent with respect to sample ids

- user-interface/src/main/java/life/qbic/datamanager/views/demo/ComponentDemo.java
- user-interface/src/main/java/life/qbic/datamanager/views/general/dialog/DialogFooter.java
You can now call build a `DialogFooter` with only a confirm button:
```java
DialogFooter.withConfirmOnly(AppDialog dialog, String confirmText)
```
This will show only one button (the primary button, that executes the confirm action).
> Provide one button app dialog

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/ontology/TIBTerminologyServiceIntegration.java
In order to mitigate network interrupts or shorter remote service down-times, this PR
introduces a very simple in-memory cache to recover in the case of term validation.
> Provide ontology term in memory cache

- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
To follow the reactive and functional style of the new service API, exceptions must not be thrown but provided wrapped as Mono or Flux.
> Provide exception API documentation

- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectServiceImpl.java
- project-management/src/main/java/life/qbic/projectmanagement/application/authorization/ReactiveSecurityContextUtils.java
- project-management/src/main/java/life/qbic/projectmanagement/application/sample/SampleInformationService.java
- project-management/src/test/groovy/life/qbic/projectmanagement/application/api/AsyncProjectServiceImplTest.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleDetailsComponent.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/SampleInformationMain.java
- user-interface/src/main/resources/application.properties
- user-interface/src/main/resources/messages/toast-notifications.properties
Provides the async service implementation for the sample management related requests.
> Implement API for sample management

- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectServiceImpl.java
Introduces an service API for querying experiment information for a given project identifier.
> Provide API for querying experiment information

- project-management/src/main/java/life/qbic/projectmanagement/domain/model/project/Project.java
Concurrent modification of projects is now possible due to the introduction
of an optimistic locking strategy introducing a version for every row entry
for the project aggregate.
In case of a concurrent write modification, an exception is thrown and
the retry handler of the flux jumps in with the default retry strategy we have
currently configured.
> Introduces optimistic locking for project aggregate

- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/rawdata/RawDataDownloadInformationComponent.java
The data download section link is currently broken since it does not account for different version documentation in its URL
> Fix Link within documentation for data download

- user-interface/src/main/java/life/qbic/datamanager/files/export/measurement/NgsEditFactory.java
- user-interface/src/main/java/life/qbic/datamanager/files/export/measurement/NgsRegisterFactory.java
- user-interface/src/main/java/life/qbic/datamanager/files/export/measurement/ProteomicsEditFactory.java
- user-interface/src/main/java/life/qbic/datamanager/files/export/measurement/ProteomicsRegisterFactory.java
Set the default generated row count to 2000 to avoid skipping of measurements if more than 200 measurements are registered
> Increase number of default generated rows within measurement excel sheets

- project-management/src/main/java/life/qbic/projectmanagement/domain/model/experiment/Experiment.java
To deal with race conditions, this PR introduces a version field
for the experiment object to enable optimistic locking strategy
on the database layer.
> Enable optimistic locking for experiments

- user-interface/src/main/java/life/qbic/datamanager/announcements/AnnouncementComponent.java
On initial loading, the empty announcements component is shown as styled in the css. This is fixed by initially hiding the component until announcements are shown.
> Prevent flickering of announcements

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/ontology/TIBTerminologyServiceIntegration.java
The API object from the terminology service contains an ontology name and an ontology prefix. Previously we used the ontology prefix which can be null but assumed we have the ontology name.
> Fix ontology term parsing

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/template/provider/openxml/factory/SampleUpdateFactory.java
- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/RegisterSampleBatchDialog.java
Sample registration was not possible due to a NullPointerException. A validation request required a request id which was always null. Further sample update was not possible due to a wrong comparison of Long values. 
This PR fixes both issues.
> Fixes sample registration and update issues

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/template/provider/openxml/factory/SampleInformationFactory.java
Fixes incorrect comparison of Long values in the sample metadata download.
Previous to this PR, no sample metadata excel file could be obtained due to incorrect comparison of Long values. (Long values > 127 break with `==` comparison)
> Fix sample metadata download

- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectService.java
- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectServiceImpl.java
- project-management/src/main/java/life/qbic/projectmanagement/application/measurement/MeasurementService.java
- project-management/src/test/groovy/life/qbic/projectmanagement/application/api/AsyncProjectServiceImplTest.java
- user-interface/src/main/java/life/qbic/datamanager/views/general/dialog/AppDialog.java
- user-interface/src/main/java/life/qbic/datamanager/views/general/dialog/DialogBody.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/MeasurementMain.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/measurements/registration/MeasurementUpload.java
- user-interface/src/main/resources/messages/toast-notifications.properties
Takes the validation request input after the user confirmed the measurement action and
performs the actual metadata registration for NGS.
The service API has been adjusted to the existing structure request form.
> Enable measurement registration NGS with the new dialog and service

- project-management/src/main/java/life/qbic/projectmanagement/domain/model/project/Contact.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/info/ProjectSummaryComponent.java
For user accounts without any orcid identifier linked, self assignment for project contacts was impossible. This is fixed now.
> Fixes project creation with self-assigned contacts

- user-interface/src/main/java/life/qbic/datamanager/views/general/upload/UploadWithDisplay.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/EditSampleBatchDialog.java
- user-interface/src/main/java/life/qbic/datamanager/views/projects/project/samples/registration/batch/RegisterSampleBatchDialog.java
Previously unspecific errors during file upload were only shown to the user but not logged on the server. To improve system stability and maintenance it is important to log the cause of the issues to address the underlying problem.
> Add logging for unspecific upload errors

- project-management/src/main/java/life/qbic/projectmanagement/application/api/AsyncProjectServiceImpl.java
Addresses https://github.com/qbicsoftware/data-manager-app/issues/1216
The security context was not set correctly for the sample retrieval. No security context was written into the reactor context. This PR fixes this bug.
> Fix wrong security context propagation leading to AccessDenied Exception

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/CachedOrganisationRepository.java
[Last week](https://github.com/ror-community/ror-api/releases/tag/1.15.0) the ror API default URL was changed to return the v2 schema instead of the v1 schema. 
This leads to [test failures](https://github.com/qbicsoftware/data-manager-app/actions/runs/16812073098/job/47619626819) since the v2 API returns a list of names instead of a singular name as before. 
Details about the schema differences can be found in the ror [readme](https://ror.readme.io/docs/schema-v2)
**How to fix**
Specified that v1 should be used until we decide if we want to incorporate the v2 in our system. (Would need an overhaul of the objectmapper extracting the information from the returned json).
> Specify Schema version to v1 in ror API

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/project/ProjectRepositoryImpl.java
- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/project/QbicProjectRepo.java
- project-management/src/main/java/life/qbic/projectmanagement/application/ProjectInformationService.java
- project-management/src/main/java/life/qbic/projectmanagement/domain/repository/ProjectRepository.java
Will ignore job flooding from concurrent project update requests.
> Use pessimistic lock to address bursts

- project-management/src/main/java/life/qbic/projectmanagement/application/measurement/MeasurementService.java
- project-management/src/main/java/life/qbic/projectmanagement/application/measurement/validation/MeasurementNGSValidator.java
- project-management/src/main/java/life/qbic/projectmanagement/application/measurement/validation/MeasurementProteomicsValidator.java
Fixes false positive validation during measurement update, in case the measurement ID is missing.
Previously users were able to upload measurement update sheets with missing measurement IDs, and the validation would pass.
> Check for missing measurement ID on update validation

- project-management/src/main/java/life/qbic/projectmanagement/domain/model/experiment/Experiment.java
Prevents object mapping exceptions for null values. Remove deprecated and unused columns from the object mapping as to prevent conflicts during runtime.
Leave the value to the databases default value.
```
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement [Column 'analyteIconName' cannot be null] [insert into experiments_datamanager (analyteIconName,experimentName,speciesIconName,specimenIconName,version,id) values (?,?,?,?,?,?)]
```
> Remove unused columns from object

- project-management-infrastructure/src/main/java/life/qbic/projectmanagement/infrastructure/ontology/TIBTerminologyServiceIntegration.java
Without a type definition all types of `class,property,individual,ontology` are returned. As `property` does not provide a parseable curie/obo_id, our integration fails for every query where a property or ontology is returned. By specifying the type to be a `class`, we get only expected results.
Documentation on the API:
https://api.terminology.tib.eu/swagger-ui/index.html?urls.primaryName=version1
> Fix ontology query failing when properties match the search term
